name: "Hub Purge"
description: "Action to clear GitHub image caches."
inputs:
  repository:
    description: Repository name with owner.
    required: false
  branch:
    description: Branch name.
    required: false
  path:
    description: |
      The path to the file containing the images for which you want to clear the cache.
      Multiple paths can also be specified by separating them with a newline.
    required: false
    default: README.md
runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: "trash-2"
  color: "gray-dark"
